In [1]:
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder

In [53]:
data = pd.read_excel(r'D:\Data_Science\DS_Files\dataGYM.xlsx')

In [54]:
data.head()

Age  Height  weight  BMI            Class  \
0   54     4.1      86   40  Extremely obese   
1   53     4.1      91   42  Extremely obese   
2   27     4.1      95   44  Extremely obese   
3   45     4.1     100   46  Extremely obese   
4   41     4.1     104   48  Extremely obese   

                                          Prediction  
0  Extremely obese--normal exercise+yoga+heavy di...  
1  Extremely obese--normal exercise+yoga+heavy di...  
2  Extremely obese--normal exercise+yoga+heavy di...  
3  Extremely obese--normal exercise+yoga+heavy di...  
4  Extremely obese--normal exercise+yoga+heavy di...

In [55]:
df = data.copy()
del df['BMI']
del df['Class']
label_encoder = LabelEncoder()
df['Prediction'] = label_encoder.fit_transform(df['Prediction'])

In [56]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [57]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=0)

model_GYM = RandomForestClassifier(n_estimators=20)

model_GYM.fit(X_train, y_train)

print(model_GYM)

RandomForestClassifier(n_estimators=20)


In [59]:
# make predictions
expected = y_test
predicted = model_GYM.predict(X_test)

In [61]:
# summarize the fit of the model
#Correction
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

              precision    recall  f1-score   support

           0       0.81      0.97      0.89        36
           1       0.72      0.84      0.77        49
           2       0.82      0.79      0.81        53
           3       0.86      0.65      0.74        46
           4       0.90      0.87      0.88        52

    accuracy                           0.82       236
   macro avg       0.82      0.82      0.82       236
weighted avg       0.82      0.82      0.82       236

[[35  0  1  0  0]
 [ 0 41  1  2  5]
 [ 8  0 42  3  0]
 [ 0  9  7 30  0]
 [ 0  7  0  0 45]]


In [62]:
import pickle

pickle.dump(model_GYM, open("Model_GYM.pkl", "wb"))

model = pickle.load(open("Model_GYM.pkl", "rb"))

print(model.predict([[40,5.6,70]]))

[1]
